camera:
  viewAngle: 0.65
  Default:
    fov: 60
    near: 1
    far: 300
  Near:
    fov: 60
    near: 1
    far: 200
  Overhead:
    fov: 60
    near: 1
    far: 100
  Map:
    fov: 70
    near: 1
    far: 4000
  laneWidth: 4.5 # original 3.32
  laneWidthToViewDistanceRatio: 5
ground:
  defaults:
    mpp: 0.125
    xres: 8192
    yres: 8192
    xorigin: 4096
    yorigin: 4096
    type: default # default or tile
    tileRange: 4
  sunnyvale_big_loop:
    mpp: 0.125
    xres: 24576
    yres: 16384
    xorigin: 587392
    yorigin: 4140800
    type: default # default or tile
    tileRange: 4
planning:
  # The minimum interval between two consecutive
  minInterval: 0.1
  defaults:
    width: 1.4
options:
  defaults:
    enableSimControl: false
    showModuleController: false
    showMenu: false
    showPOI: false
    enableVoiceCommand: false
    showPNCMonitor: false
    showRouteEditingBar: false
    showDataRecorder: false
    showTasks: true
    showVideo: false
    showPlanningCar: false
    showPlanningReference: false
    showPlaningDpOptimizer: false
    showPlanningQpOptimizer: false
    showPlanning: true
    showDecisionMain: true
    showDecisionObstacle: true
    showRouting: true
    showPerceptionLaneMarker: false
    showPredictionMajor: true
    showPredictionMinor: true
    showObstaclesVehicle: true
    showObstaclesPedestrian: true
    showObstaclesBicycle: true
    showObstaclesUnknownMovable: true
    showObstaclesUnknownUnmovable: true
    showObstaclesUnknown: true
    showObstaclesVirtual: false
    showObstaclesCipv: true
    showObstaclesVelocity: true
    showObstaclesHeading: true
    showObstaclesId: true
    showPointCloud: false
    showPositionGps: false
    showPositionLocalization: true
    showMapCrosswalk: true
    showMapClearArea: true
    showMapJunction: false
    showMapLane: true
    showMapRoad: false
    showMapSignal: true
    showMapStopSign: true
    cameraAngle: Default

navigation:
  # possible options: BaiduMap or GoogleMap
  map: "BaiduMap"

  # Google Map API: "https://maps.google.com/maps/api/js"
  # Baidu Map API: "https://api.map.baidu.com/api?v=3.0&ak=0kKZnWWhXEPfzIkklmzAa3dZ&callback=initMap"
  mapAPiUrl: "https://api.map.baidu.com/api?v=3.0&ak=0kKZnWWhXEPfzIkklmzAa3dZ&callback=initMap"

debug:
  # Turn this on for monitor related debugging
  autoMonitorMessage: false
  performanceMonitor: false
server:
  port: 8888
